
USE master;
GO
ALTER DATABASE QAECM_Reg161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg161
SET MULTI_USER;
GO

RESTORE DATABASE QAECM_Reg161 FROM DATABASE_SNAPSHOT = 'QAECM_Reg161_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAReporting_Reg161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAReporting_Reg161
SET MULTI_USER;
GO

RESTORE DATABASE QAReporting_Reg161 FROM DATABASE_SNAPSHOT = 'QAReporting_Reg161_Snapshot';
GO 




USE master;
GO
ALTER DATABASE QAPrices_Reg161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg161
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg161 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg161_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg161
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg161 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg161_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QASystem_Reg161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QASystem_Reg161
SET MULTI_USER;
GO

RESTORE DATABASE QASystem_Reg161 FROM DATABASE_SNAPSHOT = 'QASystem_Reg161_Snapshot';
GO 

