
USE master;
GO
ALTER DATABASE QAECM_Reg152
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg152
SET MULTI_USER;
GO


RESTORE DATABASE QAECM_Reg152 FROM DATABASE_SNAPSHOT = 'QAECM_Reg152_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAPrices_Reg152
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg152
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg152 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg152_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg152
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg152
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg152 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg152_Snapshot';
GO 