USE master;
GO
ALTER DATABASE VizECM_171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizECM_171
SET MULTI_USER;
GO

RESTORE DATABASE VizECM_171 FROM DATABASE_SNAPSHOT = 'VizECM_171_Snapshot';
GO

USE master;
GO
ALTER DATABASE VizReporting_171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizReporting_171
SET MULTI_USER;
GO

RESTORE DATABASE VizReporting_171 FROM DATABASE_SNAPSHOT = 'VizReporting_171_Snapshot';
GO 