
USE master;
GO
ALTER DATABASE QAECM_Reg163
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg163
SET MULTI_USER;
GO

RESTORE DATABASE QAECM_Reg163 FROM DATABASE_SNAPSHOT = 'QAECM_Reg163_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAReporting_Reg163
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAReporting_Reg163
SET MULTI_USER;
GO

RESTORE DATABASE QAReporting_Reg163 FROM DATABASE_SNAPSHOT = 'QAReporting_Reg163_Snapshot';
GO 




USE master;
GO
ALTER DATABASE QAPrices_Reg163
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg163
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg163 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg163_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg163
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg163
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg163 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg163_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QASystem_Reg163
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QASystem_Reg163
SET MULTI_USER;
GO

RESTORE DATABASE QASystem_Reg163 FROM DATABASE_SNAPSHOT = 'QASystem_Reg163_Snapshot';
GO 

