
USE master;
GO
ALTER DATABASE QAECM_Reg153
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg153
SET MULTI_USER;
GO


RESTORE DATABASE QAECM_Reg153 FROM DATABASE_SNAPSHOT = 'QAECM_Reg153_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAPrices_Reg153
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg153
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg153 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg153_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg153
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg153
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg153 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg153_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QASystem_Reg153
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QASystem_Reg153
SET MULTI_USER;
GO

RESTORE DATABASE QASystem_Reg153 FROM DATABASE_SNAPSHOT = 'QASystem_Reg153_Snapshot';
GO 