USE master;
GO
ALTER DATABASE VizECM_181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizECM_181
SET MULTI_USER;
GO

RESTORE DATABASE VizECM_181 FROM DATABASE_SNAPSHOT = 'VizECM_181_Snapshot';
GO

USE master;
GO
ALTER DATABASE VizReporting_181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizReporting_181
SET MULTI_USER;
GO

RESTORE DATABASE VizReporting_181 FROM DATABASE_SNAPSHOT = 'VizReporting_181_Snapshot';
GO 