USE master;
GO
ALTER DATABASE VizECM_161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizECM_161
SET MULTI_USER;
GO

RESTORE DATABASE VizECM_161 FROM DATABASE_SNAPSHOT = 'VizECM_161_Snapshot';
GO

USE master;
GO
ALTER DATABASE VizReporting_161
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizReporting_161
SET MULTI_USER;
GO

RESTORE DATABASE VizReporting_161 FROM DATABASE_SNAPSHOT = 'VizReporting_161_Snapshot';
GO 