USE master;
GO
ALTER DATABASE VizECM_172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizECM_172
SET MULTI_USER;
GO

RESTORE DATABASE VizECM_172 FROM DATABASE_SNAPSHOT = 'VizECM_172_Snapshot';
GO

USE master;
GO
ALTER DATABASE VizReporting_172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizReporting_172
SET MULTI_USER;
GO

RESTORE DATABASE VizReporting_172 FROM DATABASE_SNAPSHOT = 'VizReporting_172_Snapshot';
GO 