USE master;
GO
ALTER DATABASE VizECM_162
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizECM_162
SET MULTI_USER;
GO

RESTORE DATABASE VizECM_162 FROM DATABASE_SNAPSHOT = 'VizECM_162_Snapshot';
GO

USE master;
GO
ALTER DATABASE VizReporting_162
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE VizReporting_162
SET MULTI_USER;
GO

RESTORE DATABASE VizReporting_162 FROM DATABASE_SNAPSHOT = 'VizReporting_162_Snapshot';
GO 