
USE master;
GO
ALTER DATABASE QAECM_Reg171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg171
SET MULTI_USER;
GO

RESTORE DATABASE QAECM_Reg171 FROM DATABASE_SNAPSHOT = 'QAECM_Reg171_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAReporting_Reg171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAReporting_Reg171
SET MULTI_USER;
GO

RESTORE DATABASE QAReporting_Reg171 FROM DATABASE_SNAPSHOT = 'QAReporting_Reg171_Snapshot';
GO 




USE master;
GO
ALTER DATABASE QAPrices_Reg171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg171
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg171 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg171_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg171
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg171 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg171_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QASystem_Reg171
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QASystem_Reg171
SET MULTI_USER;
GO

RESTORE DATABASE QASystem_Reg171 FROM DATABASE_SNAPSHOT = 'QASystem_Reg171_Snapshot';
GO 

