
USE master;
GO
ALTER DATABASE QAECM_Reg172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg172
SET MULTI_USER;
GO

RESTORE DATABASE QAECM_Reg172 FROM DATABASE_SNAPSHOT = 'QAECM_Reg172_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAReporting_Reg172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAReporting_Reg172
SET MULTI_USER;
GO

RESTORE DATABASE QAReporting_Reg172 FROM DATABASE_SNAPSHOT = 'QAReporting_Reg172_Snapshot';
GO 




USE master;
GO
ALTER DATABASE QAPrices_Reg172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg172
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg172 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg172_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg172
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg172 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg172_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QASystem_Reg172
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QASystem_Reg172
SET MULTI_USER;
GO

RESTORE DATABASE QASystem_Reg172 FROM DATABASE_SNAPSHOT = 'QASystem_Reg172_Snapshot';
GO 

