
USE master;
GO
ALTER DATABASE QAECM_Reg181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg181
SET MULTI_USER;
GO

RESTORE DATABASE QAECM_Reg181 FROM DATABASE_SNAPSHOT = 'QAECM_Reg181_Snapshot';
GO

USE master;
GO
ALTER DATABASE QAReporting_Reg181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAReporting_Reg181
SET MULTI_USER;
GO

RESTORE DATABASE QAReporting_Reg181 FROM DATABASE_SNAPSHOT = 'QAReporting_Reg181_Snapshot';
GO 




USE master;
GO
ALTER DATABASE QAPrices_Reg181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg181
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg181 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg181_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg181
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg181 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg181_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QASystem_Reg181
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QASystem_Reg181
SET MULTI_USER;
GO

RESTORE DATABASE QASystem_Reg181 FROM DATABASE_SNAPSHOT = 'QASystem_Reg181_Snapshot';
GO 

