
USE master;
GO
ALTER DATABASE QAECM_Reg151
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAECM_Reg151
SET MULTI_USER;
GO


RESTORE DATABASE QAECM_Reg151 FROM DATABASE_SNAPSHOT = 'QAECM_Reg151_Snapshot';
GO

USE master;
GO
ALTER DATABASE QADPrices_Reg151
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QAPrices_Reg151
SET MULTI_USER;
GO

RESTORE DATABASE QAPrices_Reg151 FROM DATABASE_SNAPSHOT = 'QAPrices_Reg151_Snapshot';
GO 

USE master;
GO
ALTER DATABASE QADatawareHouse_Reg151
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE QADatawareHouse_Reg151
SET MULTI_USER;
GO

RESTORE DATABASE QADatawareHouse_Reg151 FROM DATABASE_SNAPSHOT = 'QADatawareHouse_Reg151_Snapshot';
GO 