//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElvizTestUtils.InternalJobService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobCriteria", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class JobCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastRunResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastRunTimeUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastRunResult {
            get {
                return this.LastRunResultField;
            }
            set {
                if ((object.ReferenceEquals(this.LastRunResultField, value) != true)) {
                    this.LastRunResultField = value;
                    this.RaisePropertyChanged("LastRunResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastRunTimeUtc {
            get {
                return this.LastRunTimeUtcField;
            }
            set {
                if ((this.LastRunTimeUtcField.Equals(value) != true)) {
                    this.LastRunTimeUtcField = value;
                    this.RaisePropertyChanged("LastRunTimeUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobExecutionRequest", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class JobExecutionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> OptionalParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobId {
            get {
                return this.JobIdField;
            }
            set {
                if ((this.JobIdField.Equals(value) != true)) {
                    this.JobIdField = value;
                    this.RaisePropertyChanged("JobId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> OptionalParameters {
            get {
                return this.OptionalParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionalParametersField, value) != true)) {
                    this.OptionalParametersField = value;
                    this.RaisePropertyChanged("OptionalParameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobExecutionStatus", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class JobExecutionStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutionId {
            get {
                return this.ExecutionIdField;
            }
            set {
                if ((this.ExecutionIdField.Equals(value) != true)) {
                    this.ExecutionIdField = value;
                    this.RaisePropertyChanged("ExecutionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatusRequest", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class JobStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutionId {
            get {
                return this.ExecutionIdField;
            }
            set {
                if ((this.ExecutionIdField.Equals(value) != true)) {
                    this.ExecutionIdField = value;
                    this.RaisePropertyChanged("ExecutionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobLogCriteria", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class JobLogCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutionId {
            get {
                return this.ExecutionIdField;
            }
            set {
                if ((this.ExecutionIdField.Equals(value) != true)) {
                    this.ExecutionIdField = value;
                    this.RaisePropertyChanged("ExecutionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityField, value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogEntry", Namespace="http://bradyplc.com/etrm/Jobs/v1")]
    [System.SerializableAttribute()]
    public partial class LogEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityField, value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStampUtc {
            get {
                return this.TimeStampUtcField;
            }
            set {
                if ((this.TimeStampUtcField.Equals(value) != true)) {
                    this.TimeStampUtcField = value;
                    this.RaisePropertyChanged("TimeStampUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bradyplc.com/etrm/Jobs/v1", ConfigurationName="InternalJobService.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobs", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobsResponse")]
        ElvizTestUtils.InternalJobService.Job[] QueryJobs(ElvizTestUtils.InternalJobService.JobCriteria jobCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobs", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobsResponse")]
        System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.Job[]> QueryJobsAsync(ElvizTestUtils.InternalJobService.JobCriteria jobCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/SubmitJobExecution", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/SubmitJobExecutionResponse")]
        ElvizTestUtils.InternalJobService.JobExecutionStatus SubmitJobExecution(ElvizTestUtils.InternalJobService.JobExecutionRequest jobExecutionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/SubmitJobExecution", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/SubmitJobExecutionResponse")]
        System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.JobExecutionStatus> SubmitJobExecutionAsync(ElvizTestUtils.InternalJobService.JobExecutionRequest jobExecutionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/GetExecutionStatus", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/GetExecutionStatusResponse")]
        ElvizTestUtils.InternalJobService.JobExecutionStatus GetExecutionStatus(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/GetExecutionStatus", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/GetExecutionStatusResponse")]
        System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.JobExecutionStatus> GetExecutionStatusAsync(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/WaitForExecutionStatusChange", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/WaitForExecutionStatusChangeResponse" +
            "")]
        ElvizTestUtils.InternalJobService.JobExecutionStatus WaitForExecutionStatusChange(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest, int statusChangeWaitSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/WaitForExecutionStatusChange", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/WaitForExecutionStatusChangeResponse" +
            "")]
        System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.JobExecutionStatus> WaitForExecutionStatusChangeAsync(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest, int statusChangeWaitSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobExecutionLog", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobExecutionLogResponse")]
        ElvizTestUtils.InternalJobService.LogEntry[] QueryJobExecutionLog(ElvizTestUtils.InternalJobService.JobLogCriteria jobLogRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobExecutionLog", ReplyAction="http://bradyplc.com/etrm/Jobs/v1/IJobService/QueryJobExecutionLogResponse")]
        System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.LogEntry[]> QueryJobExecutionLogAsync(ElvizTestUtils.InternalJobService.JobLogCriteria jobLogRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : ElvizTestUtils.InternalJobService.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<ElvizTestUtils.InternalJobService.IJobService>, ElvizTestUtils.InternalJobService.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ElvizTestUtils.InternalJobService.Job[] QueryJobs(ElvizTestUtils.InternalJobService.JobCriteria jobCriteria) {
            return base.Channel.QueryJobs(jobCriteria);
        }
        
        public System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.Job[]> QueryJobsAsync(ElvizTestUtils.InternalJobService.JobCriteria jobCriteria) {
            return base.Channel.QueryJobsAsync(jobCriteria);
        }
        
        public ElvizTestUtils.InternalJobService.JobExecutionStatus SubmitJobExecution(ElvizTestUtils.InternalJobService.JobExecutionRequest jobExecutionRequest) {
            return base.Channel.SubmitJobExecution(jobExecutionRequest);
        }
        
        public System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.JobExecutionStatus> SubmitJobExecutionAsync(ElvizTestUtils.InternalJobService.JobExecutionRequest jobExecutionRequest) {
            return base.Channel.SubmitJobExecutionAsync(jobExecutionRequest);
        }
        
        public ElvizTestUtils.InternalJobService.JobExecutionStatus GetExecutionStatus(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest) {
            return base.Channel.GetExecutionStatus(jobStatusRequest);
        }
        
        public System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.JobExecutionStatus> GetExecutionStatusAsync(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest) {
            return base.Channel.GetExecutionStatusAsync(jobStatusRequest);
        }
        
        public ElvizTestUtils.InternalJobService.JobExecutionStatus WaitForExecutionStatusChange(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest, int statusChangeWaitSeconds) {
            return base.Channel.WaitForExecutionStatusChange(jobStatusRequest, statusChangeWaitSeconds);
        }
        
        public System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.JobExecutionStatus> WaitForExecutionStatusChangeAsync(ElvizTestUtils.InternalJobService.JobStatusRequest jobStatusRequest, int statusChangeWaitSeconds) {
            return base.Channel.WaitForExecutionStatusChangeAsync(jobStatusRequest, statusChangeWaitSeconds);
        }
        
        public ElvizTestUtils.InternalJobService.LogEntry[] QueryJobExecutionLog(ElvizTestUtils.InternalJobService.JobLogCriteria jobLogRequest) {
            return base.Channel.QueryJobExecutionLog(jobLogRequest);
        }
        
        public System.Threading.Tasks.Task<ElvizTestUtils.InternalJobService.LogEntry[]> QueryJobExecutionLogAsync(ElvizTestUtils.InternalJobService.JobLogCriteria jobLogRequest) {
            return base.Channel.QueryJobExecutionLogAsync(jobLogRequest);
        }
    }
}
