if not exists (select * from Calendars where CalendarName='UK bank holidays')
       begin
       Insert into Calendars(CalendarId, CalendarName) Values ((select Max(CalendarId) from Calendars)+1, 'UK bank holidays')
       end    

declare @calid integer;
set @calid =(select calendarid from Calendars where dbo.Calendars.CalendarName='UK bank holidays')
delete from Holidays where CalendarId = @calid 

insert into Holidays(HolidayDate, CalendarId)
values ('2010-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-04-02', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-04-05', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-05-03', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-05-31', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-08-30', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-12-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-12-27', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2010-12-28', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2011-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-04-22', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-04-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-05-02', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-05-30', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-08-29', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-12-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2011-12-27', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2012-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-01-02', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-04-06', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-04-09', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-05-07', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-06-04', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-06-05', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-08-27', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2012-12-26', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2013-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-03-29', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-04-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-06-05', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-05-27', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-08-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2013-12-26', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2014-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-04-18', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-04-21', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-05-05', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-05-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-08-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2014-12-26', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2015-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-04-03', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-04-06', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-05-04', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-05-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-08-31', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-12-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2015-12-28', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2016-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-03-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-03-28', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-05-02', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-05-30', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-08-29', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-12-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2016-12-27', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2017-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-01-02', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-04-14', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-04-17', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-05-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-05-29', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-08-28', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2017-12-26', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2018-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-03-30', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-04-02', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-05-07', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-05-28', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-08-27', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2018-12-26', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2019-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-04-19', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-04-22', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-05-06', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-05-27', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-08-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2019-12-26', @calid)

insert into Holidays(HolidayDate, CalendarId)
values ('2020-01-01', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-04-10', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-04-13', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-05-04', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-05-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-08-31', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-12-25', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-12-26', @calid)
insert into Holidays(HolidayDate, CalendarId)
values ('2020-12-28', @calid)

