//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonitorType()
        {
            this.Monitors = new HashSet<Monitor>();
        }
    
        public int MonitorTypeId { get; set; }
        public string MonitorTypeName { get; set; }
        public string EtrmName { get; set; }
        public string DefaultQuery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitor> Monitors { get; set; }
    }
}
