//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monitor()
        {
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int MonitorId { get; set; }
        public int WorkspaceId { get; set; }
        public int MonitorTypeId { get; set; }
        public string MonitorName { get; set; }
        [DataType(DataType.MultilineText)]
        public string Query { get; set; }
        public double Tollerance { get; set; }
    
        public virtual MonitorType MonitorType { get; set; }
        public virtual Workspace Workspace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
