//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreTestWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PretestModelEntities : DbContext
    {
        public PretestModelEntities()
            : base("name=PretestModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MonitorType> MonitorTypes { get; set; }
        public virtual DbSet<PreTest> PreTests { get; set; }
        public virtual DbSet<ProdEnvRun> ProdEnvRuns { get; set; }
        public virtual DbSet<TestEnvRun> TestEnvRuns { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<SqlServer> SqlServers { get; set; }
        public virtual DbSet<Workspace> Workspaces { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
    }
}
