//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreTest()
        {
            this.Workspaces = new HashSet<Workspace>();
        }
    
        public int PreTestId { get; set; }
        public string Name { get; set; }
        public int ProdServerId { get; set; }
        public int TestServerId { get; set; }
        public bool Active { get; set; }
    
        public virtual Server ProdServer { get; set; }
        public virtual Server TestServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workspace> Workspaces { get; set; }
    }
}
