//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdEnvRun
    {
        public int ProdEnvRunId { get; set; }
        public int WorkspaceId { get; set; }
        public System.DateTime RunStartTime { get; set; }
        public string JobResult { get; set; }

        [DataType(DataType.MultilineText)]
        public string ProdServerLog { get; set; }
        public string EtrmVersion { get; set; }
    
        public virtual Workspace Workspace { get; set; }
    }
}
