//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqlServer()
        {
            this.Servers = new HashSet<Server>();
        }
    
        public int SqlServerId { get; set; }
        public string SqlServerName { get; set; }
        public string SqlUserName { get; set; }
        public string SqlPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Server> Servers { get; set; }
    }
}
