//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestResultId { get; set; }
        public int MonitorId { get; set; }
        public int TestEnvRunId { get; set; }
        public string TestResultStatus { get; set; }
        public string TestResultMessage { get; set; }
    
        public virtual TestEnvRun TestEnvRun { get; set; }
        public virtual Monitor Monitor { get; set; }
    }
}
