//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEnvRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestEnvRun()
        {
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int TestEnvRunId { get; set; }
        public int WorkspaceId { get; set; }
        public System.DateTime RunStartTime { get; set; }
        public string JobResult { get; set; }
        public string TestServerJobLog { get; set; }
        public string EtrmVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
        public virtual Workspace Workspace { get; set; }
    }
}
