//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;

namespace PreTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workspace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workspace()
        {
            this.ProdEnvRuns = new HashSet<ProdEnvRun>();
            this.TestEnvRuns = new HashSet<TestEnvRun>();
            this.Monitors = new HashSet<Monitor>();
        }
    
        public int WorkspaceId { get; set; }
        public int PreTestId { get; set; }
        public string WorkspaceName { get; set; }
        public string ErmEcm { get; set; }

        [DataType(DataType.DateTime)]
        public System.DateTime ReportDate { get; set; }
        public int TimeOutInSeconds { get; set; }
        public bool IsRunningInProdEnv { get; set; }
        public bool IsRunningInTestEnv { get; set; }
    
        public virtual PreTest PreTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdEnvRun> ProdEnvRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestEnvRun> TestEnvRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitor> Monitors { get; set; }
    }
}
