@echo off
set version=2012.3
set DeployServer=BERSVDEPLOY
set MsiName=CRV%version%.msi
ECHO Nightly patch is  starting on %ElvizApplServer%
echo %MsiName%
Del C:\%MsiName%
xcopy /Y  "\\%DeployServer%\INSTALLATIONS\DEP_TEMP\CRV\%version%\%MsiName%" C:\
MsiExec /X  "{DDE7CBB6-97CB-41D6-A1C7-D8EDE8AA99FF}" /qn

msiexec /i "C:\%MsiName%" /quiet INSTALLDIR=C:\Elviz  IS_SQLSERVER_SERVER=BERSV-QADB1 IS_SQLSERVER_USERNAME=EcmDbUser IS_SQLSERVER_PASSWORD=EcmDbUser IS_SQLSERVER_DATABASE=QACRV123 APP_SERVER=QA123A PORT_NUMBER=8009 NOMXHOSTIP=192.176.3.151 NOMXPORTNO=6124 NOMXUSERNAME=NPVIZTS_14 NOMXPASSWORD=Nasdaq12 CLEARONCONFIRM=1 IGNOREFEE=1
